apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: debezium-mysql-shared
  namespace: kiwi-lab
  labels:
    strimzi.io/cluster: debezium-mysql-shared
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    bigint.unsigned.handling.mode: "long"
    binary.handling.mode: "bytes"
    connect.timeout.ms: "30000"
    database.hostname: "mysql"
    database.server.id: "12345"
    database.jdbc.driver: "com.mysql.cj.jdbc.Driver"
    database.password: "${env:MYSQL_PASSWORD}"
    database.port: "3306"
    database.protocol: "jdbc:mysql"
    database.user: "${env:MYSQL_USER}"
    decimal.handling.mode: "precise"
    include.query: "false"
    include.schema.changes: "true"
    include.schema.comments: "false"
    inconsistent.schema.handling.mode: "fail"
    time.precision.mode: "connect"
    tombstones.on.delete: "false"
    topic.prefix: "debezium.mysql.shared"
    database.include.list: "beauty_db"
    table.include.list: "beauty_db.consultation,beauty_db.push_info,beauty_db.chat_room_stats,beauty_db.page,beauty_db.hospital"
    connect.keep.alive: "true"
    database.query.timeout.ms: "600000"
    database.ssl.mode: "preferred"
    enable.time.adjuster: "true"
    errors.max.retries: "-1"
    event.converting.failure.handling.mode: "fail"
    event.processing.failure.handling.mode: "fail"
    heartbeat.interval.ms: "0"
    max.batch.size: "2048"
    max.queue.size: "8192"
    max.queue.size.in.bytes: "0"
    poll.interval.ms: "500"
    provide.transaction.metadata: "false"
    skipped.operations: "t"
    snapshot.lock.timeout.ms: "0"
    snapshot.locking.mode: "none"
    snapshot.max.threads: "1"
    snapshot.mode: "no_data"
    source.struct.version: "v2"
    table.ignore.builtin: "true"
    topic.cache.size: "10000"
    topic.delimiter: "."
    topic.heartbeat.prefix: "__debezium-heartbeat"
    topic.naming.strategy: "io.debezium.schema.DefaultTopicNamingStrategy"
    use.nongraceful.disconnect: "false"
    guardrail.collections.max: "0"
    guardrail.collections.limit.action: "warn"
    transforms: "unwrap"
    transforms.unwrap.type: "io.debezium.transforms.ExtractNewRecordState"
    transforms.unwrap.delete.handling.mode: "rewrite"
    transforms.unwrap.add.fields: "source.version,source.connector,source.name,source.ts_ms,source.snapshot,source.db,source.sequence,source.ts_us,source.ts_ns,source.table,source.server_id,source.gtid,source.file,source.pos,source.row,source.thread,source.query,op,ts_ms,ts_us,ts_ns"
    schema.history.internal.kafka.topic: "__debezium.mysql.shared.schema-history"
    schema.history.internal.kafka.bootstrap.servers: "kafka-kafka-bootstrap:9092"
    schema.history.internal.kafka.recovery.poll.interval.ms: "100"
    schema.history.internal.kafka.query.timeout.ms: "3000"
    schema.history.internal.kafka.create.timeout.ms: "30000"
    schema.history.internal.kafka.recovery.attempts: "100"
    schema.history.internal.skip.unparseable.ddl: "false"
    schema.history.internal.store.only.captured.tables.ddl: "false"
    schema.history.internal.store.only.captured.databases.ddl: "false"

