apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: kiwi-lab
type: Opaque
stringData:
  access-key: minioadmin
  secret-key: minioadmin
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: s3-sink
  namespace: kiwi-lab
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.2.0
  replicas: 1
  image: s3-connect:kafka-4.2.0
  bootstrapServers: "kafka-kafka-bootstrap:9092"
  groupId: s3-sink
  configStorageTopic: __s3-sink-configs
  statusStorageTopic: __s3-sink-status
  offsetStorageTopic: __s3-sink-offsets
  template:
    connectContainer:
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
  config:
    offset.storage.replication.factor: 1
    config.storage.replication.factor: 1
    status.storage.replication.factor: 1
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://schema-registry:8081
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://schema-registry:8081
    config.providers: env
    config.providers.env.class: org.apache.kafka.common.config.provider.EnvVarConfigProvider
  resources:
    requests:
      memory: 512Mi
      cpu: "100m"
    limits:
      memory: 1Gi
      cpu: "500m"
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5