apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: s3-sink-debezium-mysql-local
  namespace: kiwi-lab
  labels:
    strimzi.io/cluster: s3-sink
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  config:
    # Connector
    format.class: "io.confluent.connect.s3.format.avro.AvroFormat"
    flush.size: "10"
    rotate.interval.ms: "-1"
    rotate.schedule.interval.ms: "60000"
    schema.cache.config: "1000"
    avro.codec: "snappy"
    # S3 (MinIO)
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    store.url: "http://minio:9000"
    s3.path.style.access.enabled: "true"
    s3.bucket.name: "kafka-s3-test"
    s3.region: "us-east-1"
    s3.part.size: "5242880"
    aws.access.key.id: "${env:AWS_ACCESS_KEY_ID}"
    aws.secret.access.key: "${env:AWS_SECRET_ACCESS_KEY}"
    # Storage
    topics.dir: "landing/debezium_mysql_local/testdb"
    # Partitioner
    partitioner.class: "io.confluent.connect.storage.partitioner.TimeBasedPartitioner"
    partition.duration.ms: "600000"
    path.format: "'ds'=YYYY-MM-dd-HH-mm"
    timezone: "UTC"
    locale: "en_US"
    # Sink
    topics.regex: "debezium.mysql.local.testdb.*"
    errors.tolerance: "none"
    errors.log.enable: "true"
    errors.log.include.messages: "true"
    # Table name routing
    transforms: "route"
    transforms.route.type: "org.apache.kafka.connect.transforms.RegexRouter"
    transforms.route.regex: "debezium\\.mysql\\.([^.]+)\\.([^.]+)\\.([^.]+)"
    transforms.route.replacement: "$3"
