apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafbat-ui
  namespace: project1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafbat-ui
  template:
    metadata:
      labels:
        app: kafbat-ui
    spec:
      containers:
        - name: kafbat-ui
          image: ghcr.io/kafbat/kafka-ui:latest
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: local-cdc
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka:9092
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
              value: local-connect
            # Strimzi가 KafkaConnect 이름으로 자동 생성하는 서비스: {name}-connect-api
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
              value: http://debezium-mysql-shared-connect-api:8083
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              value: http://schema-registry-cp-schema-registry:8081
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafbat-ui
  namespace: project1
spec:
  selector:
    app: kafbat-ui
  ports:
    - port: 8080