replicaCount: 1

kafka:
  enabled: false

externalKafka:
  brokers:
    - PLAINTEXT://kafka-kafka-bootstrap:9092
  listener:
    protocol: PLAINTEXT

avroCompatibilityLevel: backward

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m