apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kafka-ui
    repo: https://kafbat.github.io/helm-charts
    releaseName: kafbat
    namespace: kiwi-lab
    valuesInline:
      yamlApplicationConfig:
        kafka:
          clusters:
            - name: local-cdc
              bootstrapServers: kafka:9092
              kafkaConnect:
                - name: local-connect
                  address: http://debezium-mysql-shared-connect-api:8083
              schemaRegistry: http://schema-registry-cp-schema-registry:8081
