apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kafka-ui
    repo: https://kafbat.github.io/helm-charts
    version: "1.6.3"
    releaseName: kafbat
    namespace: kiwi-lab
    valuesFile: values.yaml
